// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Caterogy struct {
	ID        int16     `json:"id"`
	Category  string    `json:"category"`
	CreatedAt time.Time `json:"created_at"`
}

type Comment struct {
	ID              int64     `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	TicketID        int64     `json:"ticket_id"`
	Comments        string    `json:"comments"`
	CustomerVisible bool      `json:"customer_visible"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Ticket struct {
	ID          int64     `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	AssignedTo  uuid.UUID `json:"assigned_to"`
	Description string    `json:"description"`
	Status      int32     `json:"status"`
	Priority    int32     `json:"priority"`
	CategoryID  uuid.UUID `json:"category_id"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	UserRole          int32     `json:"user_role"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	PasswordUpdatedAt time.Time `json:"password_updated_at"`
}
