// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, category string) (Caterogy, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	GetAllCategories(ctx context.Context) ([]Caterogy, error)
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetTicket(ctx context.Context, id int64) (Ticket, error)
	GetTicketComments(ctx context.Context, arg GetTicketCommentsParams) ([]Comment, error)
	GetTicketList(ctx context.Context, arg GetTicketListParams) ([]Ticket, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserList(ctx context.Context, arg GetUserListParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Caterogy, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
